apiVersion: v1
kind: Service
metadata:
  name: student-app-api
  namespace: reactjava
spec:
  selector:
	app: student-app-api
  ports:
    - port: 9005
      targetPort: 8080
	  protocol: TCP
	  nodePort: 30065
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-api
  namespace: reactjava
spec:
  selector:
	matchLabels:
	  app: student-app-api
  replicas: 1
  template:
    metadata:
	  labels:
	    app: student-app-api
	spec:
	  containers:
		- name: student-app-api
		  image: saikannepalli/springreact:latest
		  imagePullPolicy: Always
		  ports:
			- containerPort: 8080
		  env:
			- name: MONGO_URL
			  value: mongodb://mongo:27017/dev
		  imagePullPolicy: Always
